// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB11UCuOdtBsHyMb_CzIkYDQzTJQU4LhfQ',
    appId: '1:655579448990:web:1c247399c78f4c93669d8f',
    messagingSenderId: '655579448990',
    projectId: 'chat-app-e8b88',
    authDomain: 'chat-app-e8b88.firebaseapp.com',
    storageBucket: 'chat-app-e8b88.appspot.com',
    measurementId: 'G-C7J0729RZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZNwAPcCIrw8lnH8dY7s54-kQ76ejpMQA',
    appId: '1:655579448990:android:e70d35b0add0a674669d8f',
    messagingSenderId: '655579448990',
    projectId: 'chat-app-e8b88',
    storageBucket: 'chat-app-e8b88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAg6etNFYiu0VuOSnq0CTMDNe5WIDbj9o',
    appId: '1:655579448990:ios:a2627f102ea8f119669d8f',
    messagingSenderId: '655579448990',
    projectId: 'chat-app-e8b88',
    storageBucket: 'chat-app-e8b88.appspot.com',
    iosBundleId: 'com.example.chatterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAg6etNFYiu0VuOSnq0CTMDNe5WIDbj9o',
    appId: '1:655579448990:ios:a2627f102ea8f119669d8f',
    messagingSenderId: '655579448990',
    projectId: 'chat-app-e8b88',
    storageBucket: 'chat-app-e8b88.appspot.com',
    iosBundleId: 'com.example.chatterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB11UCuOdtBsHyMb_CzIkYDQzTJQU4LhfQ',
    appId: '1:655579448990:web:f58234e66d43c442669d8f',
    messagingSenderId: '655579448990',
    projectId: 'chat-app-e8b88',
    authDomain: 'chat-app-e8b88.firebaseapp.com',
    storageBucket: 'chat-app-e8b88.appspot.com',
    measurementId: 'G-8KFT2P9E6K',
  );

}